# Generated by Django 3.2.8 on 2021-12-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
