# Generated by Django 3.2.8 on 2021-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clustering', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('recency', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('monetary', models.IntegerField()),
            ],
        ),
    ]
