# Generated by Django 3.2.8 on 2022-01-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRFM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('w_recency', models.FloatField()),
                ('w_frequency', models.FloatField()),
                ('w_monetary', models.FloatField()),
                ('score_input', models.TextField()),
            ],
        ),
    ]
