# Generated by Django 3.2.8 on 2022-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0004_weightrfm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrfm',
            name='score_input',
            field=models.TextField(null=True),
        ),
    ]
