# Generated by Django 3.2.8 on 2022-01-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0005_alter_weightrfm_score_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrfm',
            name='score_input',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
