# Generated by Django 3.2.8 on 2022-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0006_alter_weightrfm_score_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightLRFM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('w_length', models.FloatField()),
                ('w_recency', models.FloatField()),
                ('w_frequency', models.FloatField()),
                ('w_monetary', models.FloatField()),
                ('score_input', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='frequency',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='monetary',
            new_name='total_spend',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='recency',
        ),
        migrations.AddField(
            model_name='customer',
            name='aov',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_active',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
