# Generated by Django 3.2.8 on 2022-02-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0007_auto_20220209_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cluster',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
