# Generated by Django 3.2.8 on 2022-02-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0008_customer_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('telp', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('id_company', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('verified', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='id_company',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='id_company',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightlrfm',
            name='id_company',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weightrfm',
            name='id_company',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
