# Generated by Django 3.2.8 on 2022-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0009_auto_20220213_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_customer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
