# Generated by Django 3.2.8 on 2022-02-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0011_alter_weightrfm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_order',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weightrfm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
